version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backendrud:
    build: ./backendrud
    container_name: backendrud
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backendrud

volumes:
  mongo_data:
  redis_data:
