services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backendrud:
    build: ./backendrud
    container_name: backendrud
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backendrud

volumes:
  mongo_data:
